//
// Created by PC on 28/05/2026.
//

#ifndef SCHNORR_THRESHOLD_DSA_ECDSA_OPERATIONS_CODES_H
#define SCHNORR_THRESHOLD_DSA_ECDSA_OPERATIONS_CODES_H

#define RECOVERY_INFO_CODE 0x01
#define RECOVERY_START_ZKP_CODE 0x02
#define RECOVERY_PASSED_ZKP_CODE 0x03

#define RECOVERY_SIGN_MESSAGE_CODE 0x20

#define RECOVERY_COMMITMENT_R_CODE 0x04
#define RECOVERY_DECOMMITMENT_R_CODE 0x05
#define RECOVERY_COMMITMENT_R_PASSED_CODE 0x06
#define RECOVERY_COMMITMENT_S_CODE 0x07
#define RECOVERY_DECOMMITMENT_S_CODE 0x08
#define RECOVERY_COMMITMENT_S_PASSED_CODE 0x09

#define U_H_ZKP_CODE 0x10
#define C_ZKP_CODE 0x11
#define Z_ZKP_CODE 0x12

#define ABORT_CODE 0xFF


#endif //SCHNORR_THRESHOLD_DSA_ECDSA_OPERATIONS_CODES_H
