//
// Created by PC on 28/05/2026.
//

#ifndef SCHNORR_THRESHOLD_DSA_ECDSA_OPERATIONS_CODES_H
#define SCHNORR_THRESHOLD_DSA_ECDSA_OPERATIONS_CODES_H

#define RECOVERY_INFO_CODE 0x01
#define RECOVERY_PASSED_ZKP_CODE 0x02
#define RECOVERY_SIGN_MESSAGE_CODE 0x03

#define RECOVERY_COMMITMENT_R_CODE 0x04
#define RECOVERY_DECOMMITMENT_R_CODE 0x05
#define RECOVERY_COMMITMENT_S_CODE 0x07
#define RECOVERY_DECOMMITMENT_S_CODE 0x08

#define U_H_ZKP_CODE 0x10
#define C_ZKP_CODE 0x11
#define Z_ZKP_CODE 0x12
#define RECOVERY_U_H_ZKP_CODE 0x13
#define RECOVERY_C_ZKP_CODE 0x14
#define RECOVERY_Z_ZKP_CODE 0x15

#define KEYGEN_PHASE1_CODE 0x30
#define KEYGEN_DECOMMITMENT_CODE 0x31
#define KEYGEN_COMMPACK_PASSED_CODE 0x32
#define KEYGEN_M_CODE 0x33
#define KEYGEN_RECOVERY_INFO_CODE 0x34
#define KEYGEN_NIZKP_PASSED_CODE 0x35
#define KEYGEN_SHARES_PASSED_CODE 0x36
#define KEYGEN_DONE_CODE 0x37

#define SIGNING_START_CODE 0x40
#define SIGNING_R_COMMITMENT_CODE 0x41
#define SIGNING_R_DECOMMITMENT_CODE 0x42
#define SIGNING_S_COMMITMENT_CODE 0x43
#define SIGNING_S_DECOMMITMENT_CODE 0x44

#


#define ABORT_CODE 0xFF


#endif //SCHNORR_THRESHOLD_DSA_ECDSA_OPERATIONS_CODES_H
